<?php

use yii\db\Migration;
use yii\base\InvalidConfigException;
use yii\rbac\DbManager;

/**
 * Class m190209_224417_stats_robots
 */
class m190209_224417_stats_robots extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            $tableOptions = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB';
        }

        $this->createTable('{{%stats_robots}}', [
            'id'=> $this->primaryKey(11),
            'name' => $this->string(32)->notNull(),
            'regexp' => $this->string(32)->notNull(),
            'hosts' => $this->string(255)->null(),
            'type' => $this->tinyInteger(1)->null()->defaultValue(0),
            'is_badbot' => $this->boolean()->defaultValue(false),
        ], $tableOptions);

        if (!(Yii::$app->db->getTableSchema('{{%stats_visitors}}', true) === null)) {
            $this->addForeignKey(
                'fk_visitors_to_robots',
                '{{%stats_visitors}}',
                'robot_id',
                '{{%stats_robots}}',
                'id',
                'NO ACTION',
                'CASCADE'
            );
        }

        $rows = [
            ["Rambler", "rambler", 0, [], 0],
            ["GoogleBot", "googlebot", 0, [], 0],
            ["Aport", "aport", 0, [], 0],
            ["Yahoo", "yahoo", 0, [], 0],
            ["MSNbot", "msnbot", 0, [], 0],
            ["Turtle", "turtle", 0, [], 0],
            ["Mail.Ru", "mail.ru", 0, [], 0],
            ["Omsktele", "omsktele", 0, [], 0],
            ["YetiBot", "yetibot", 0, [], 0],
            ["PicSearch", "picsearch", 0, [], 0],
            ["Sape.Bot", "sape.bot", 0, [], 0],
            ["Sape_context", "sape_context", 0, [], 0],
            ["Gigabot", "gigabot", 0, [], 0],
            ["Snapbot", "snapbot", 0, [], 0],
            ["Alexa.com", "alexa.com", 0, [], 0],
            ["Megadownload.net", "megadownload.net", 0, [], 0],
            ["Askpeter.info", "askpeter.info", 0, [], 0],
            ["Igde.ru", "igde.ru", 0, [], 0],
            ["Ask.com", "ask.com", 0, [], 0],
            ["Qwartabot", "qwartabot", 0, [], 0],
            ["Yanga.co.uk", "yanga.co.uk", 0, [], 0],
            ["Scoutjet", "scoutjet", 0, [], 0],
            ["Similarpages", "similarpages", 0, [], 0],
            ["OozBot", "oozbot", 0, [], 0],
            ["Shrinktheweb.com", "shrinktheweb.com", 0, [], 0],
            ["Aboutusbot", "aboutusbot", 0, [], 0],
            ["Followsite.com", "followsite.com", 0, [], 0],
            ["Dataparksearch", "dataparksearch", 0, [], 0],
            ["Google Sitemaps", "google-sitemaps", 0, [], 0],
            ["Google appEngine", "appEngine-google", 0, [], 0],
            ["Google feedFetcher", "feedfetcher-google", 0, [], 0],
            ["Liveinternet.ru", "liveinternet.ru", 0, [], 0],
            ["Xml-Sitemaps.com", "xml-sitemaps.com", 0, [], 0],
            ["Agama", "agama", 0, [], 0],
            ["Metadatalabs.com", "metadatalabs.com", 0, [], 0],
            ["h1.hrn.ru", "h1.hrn.ru", 0, [], 0],
            ["Googlealert.com", "googlealert.com", 0, [], 0],
            ["Seo-Rus.com", "seo-rus.com", 0, [], 0],
            ["YadirectBot", "yaDirectBot", 0, [], 0],
            ["Yandeg", "yandeG", 0, [], 0],
            ["Yandex", "yandex", 0, [], 0],
            ["YandexSomething", "yandexSomething", 0, [], 0],
            ["Copyscape.com", "Copyscape.com", 0, [], 0],
            ["Adsbot-Google", "AdsBot-Google", 0, [], 0],
            ["Domaintools.com", "domaintools.com", 0, [], 0],
            ["Nigma.ru", "Nigma.ru", 0, [], 0],
            ["Bing.com", "bing.com", 0, [], 0],
            ["Dotnetdotcom", "dotnetdotcom", 0, [], 0],
            ["Aport", "aport", 0, [], 0],
            ["AWBot", "awbot", 0, [], 0],
            ["BaiDuSpider", "baiduspider", 0, [], 0],
            ["Bobby", "bobby", 0, [], 0],
            ["Boris", "boris", 0, [], 0],
            ["Bumblebee (relevare.com)", "bumblebee", 0, [], 0],
            ["CsCrawler", "cscrawler", 0, [], 0],
            ["DaviesBot", "daviesbot", 0, [], 0],
            ["ExactSeek Crawler", "exactseek", 0, [], 0],
            ["Ezresult", "ezresult", 0, [], 0],
            ["GigaBot", "gigabot", 0, [], 0],
            ["GNOD Spider", "gnodspider", 0, [], 0],
            ["Grub.org", "grub", 0, [], 0],
            ["Mirago", "henrythemiragorobot", 0, [], 0],
            ["Holmes", "holmes", 0, [], 0],
            ["InternetSeer", "internetseer", 0, [], 0],
            ["JustView", "justview", 0, [], 0],
            ["LinkBot", "linkbot", 0, [], 0],
            ["MetaGer LinkChecker", "metager\-linkchecker", 0, [], 0],
            ["LinkChecker", "linkchecker", 0, [], 0],
            ["Microsoft URL Control", "microsoft_url_control", 0, [], 0],
            ["MSIECrawler", "msiecrawler", 0, [], 0],
            ["Nagios", "nagios", 0, [], 0],
            ["Perman surfer", "perman", 0, [], 0],
            ["Pompos", "pompos", 0, [], 0],
            ["StackRambler", "rambler", 0, [], 0],
            ["Red Alert", "redalert", 0, [], 0],
            ["Shoutcast Directory Service", "shoutcast", 0, [], 0],
            ["SlySearch", "slysearch", 0, [], 0],
            ["SurveyBot", "surveybot", 0, [], 0],
            ["Turn It In", "turnitinbot", 0, [], 0],
            ["Turtle", "turtlescanner", 0, [], 0],
            ["Turtle", "turtle", 0, [], 0],
            ["Ultraseek", "ultraseek", 0, [], 0],
            ["WebClipping.com", "webclipping\.com", 0, [], 0],
            ["webcompass", "webcompass", 0, [], 0],
            ["Web Wombat Redback Spider", "wonderer", 0, [], 0],
            ["Yahoo Vertical Crawler", "yahoo\-verticalcrawler", 0, [], 0],
            ["Yandex bot", "yandex", 0, [], 0],
            ["ZealBot", "zealbot", 0, [], 0],
            ["Zyborg", "zyborg", 0, [], 0],
            ["Walhello appie", "appie", 0, [], 0],
            ["ArchitextSpider", "architext", 0, [], 0],
            ["AskJeeves", "jeeves", 0, [], 0],
            ["Bjaaland", "bjaaland", 0, [], 0],
            ["Googlebot", "googlebot", 0, [], 0],
            ["Northern Light Gulliver", "gulliver", 0, [], 0],
            ["Harvest", "harvest", 0, [], 0],
            ["ht://Dig", "htdig", 0, [], 0],
            ["LinkWalker", "linkwalker", 0, [], 0],
            ["Lycos", "lycos_", 0, [], 0],
            ["moget", "moget", 0, [], 0],
            ["Muscat Ferret", "muscatferret", 0, [], 0],
            ["Internet Shinchakubin", "myweb", 0, [], 0],
            ["Nomad", "nomad", 0, [], 0],
            ["Scooter", "scooter", 0, [], 0],
            ["Inktomi Slurp", "slurp", 0, [], 0],
            ["Voyager", "^voyager\/", 0, [], 0],
            ["weblayers", "weblayers", 0, [], 0],
            ["Antibot", "antibot", 0, [], 0],
            ["Digout4u", "digout4u", 0, [], 0],
            ["EchO!", "echo", 0, [], 0],
            ["Fast-Webcrawler", "fast\-webcrawler", 0, [], 0],
            ["Alexa (IA Archiver)", "ia_archiver", 0, [], 0],
            ["JennyBot", "jennybot", 0, [], 0],
            ["Mercator", "mercator", 0, [], 0],
            ["Netcraft", "netcraft", 0, [], 0],
            ["Petersnews", "petersnews", 0, [], 0],
            ["Unlost Web Crawler", "unlost_web_crawler", 0, [], 0],
            ["Voila", "voila", 0, [], 0],
            ["WebBase", "webbase", 0, [], 0],
            ["WISENutbot", "wisenutbot", 0, [], 0],
            ["Fish search", "[^a]fish", 0, [], 0],
            ["ABCdatos BotLink", "abcdatos", 0, [], 0],
            ["Acme.Spider", "acme\.spider", 0, [], 0],
            ["Ahoy! The Homepage Finder", "ahoythehomepagefinder", 0, [], 0],
            ["Alkaline", "alkaline", 0, [], 0],
            ["Anthill", "anthill", 0, [], 0],
            ["Arachnophilia", "arachnophilia", 0, [], 0],
            ["Arale", "arale", 0, [], 0],
            ["Araneo", "araneo", 0, [], 0],
            ["Aretha", "aretha", 0, [], 0],
            ["ARIADNE", "ariadne", 0, [], 0],
            ["arks", "arks", 0, [], 0],
            ["ASpider (Associative Spider)", "aspider", 0, [], 0],
            ["ATN Worldwide", "atn\.txt", 0, [], 0],
            ["Atomz.com Search Robot", "atomz", 0, [], 0],
            ["AURESYS", "auresys", 0, [], 0],
            ["BackRub", "backrub", 0, [], 0],
            ["BBot", "bbot", 0, [], 0],
            ["Big Brother", "bigbrother", 0, [], 0],
            ["BlackWidow", "blackwidow", 0, [], 0],
            ["Die Blinde Kuh", "blindekuh", 0, [], 0],
            ["Bloodhound", "bloodhound", 0, [], 0],
            ["Borg-Bot", "borg\-bot", 0, [], 0],
            ["bright.net caching robot", "brightnet", 0, [], 0],
            ["BSpider", "bspider", 0, [], 0],
            ["CACTVS Chemistry Spider", "cactvschemistryspider", 0, [], 0],
            ["Calif", "calif[^r]", 0, [], 0],
            ["Cassandra", "cassandra", 0, [], 0],
            ["Digimarc Marcspider/CGI", "cgireader", 0, [], 0],
            ["Checkbot", "checkbot", 0, [], 0],
            ["ChristCrawler.com", "christcrawler", 0, [], 0],
            ["churl", "churl", 0, [], 0],
            ["cIeNcIaFiCcIoN.nEt", "cienciaficcion", 0, [], 0],
            ["Collective", "collective", 0, [], 0],
            ["Combine System", "combine", 0, [], 0],
            ["Conceptbot", "conceptbot", 0, [], 0],
            ["CoolBot", "coolbot", 0, [], 0],
            ["Web Core / Roots", "core", 0, [], 0],
            ["XYLEME Robot", "cosmos", 0, [], 0],
            ["Internet Cruiser Robot", "cruiser", 0, [], 0],
            ["Cusco", "cusco", 0, [], 0],
            ["CyberSpyder Link Test", "cyberspyder", 0, [], 0],
            ["Desert Realm Spider", "desertrealm", 0, [], 0],
            ["DeWeb(c) Katalog/Index", "deweb", 0, [], 0],
            ["DienstSpider", "dienstspider", 0, [], 0],
            ["Digger", "digger", 0, [], 0],
            ["Digital Integrity Robot", "diibot", 0, [], 0],
            ["Direct Hit Grabber", "direct_hit", 0, [], 0],
            ["DNAbot", "dnabot", 0, [], 0],
            ["DownLoad Express", "download_express", 0, [], 0],
            ["DragonBot", "dragonbot", 0, [], 0],
            ["DWCP (Dridus' Web Cataloging P", "dwcp", 0, [], 0],
            ["e-collector", "e\-collector", 0, [], 0],
            ["EbiNess", "ebiness", 0, [], 0],
            ["ELFINBOT", "elfinbot", 0, [], 0],
            ["Emacs-w3 Search Engine", "emacs", 0, [], 0],
            ["ananzi", "emcspider", 0, [], 0],
            ["Esther", "esther", 0, [], 0],
            ["Evliya Celebi", "evliyacelebi", 0, [], 0],
            ["FastCrawler", "fastcrawler", 0, [], 0],
            ["Fluid Dynamics Search Engine r", "fdse", 0, [], 0],
            ["Felix IDE", "felix", 0, [], 0],
            ["FetchRover", "fetchrover", 0, [], 0],
            ["Femtosearch", "FemtosearchBot", 0, [], 0],
            ["Fido", "fido", 0, [], 0],
            ["Finnish", "finnish", 0, [], 0],
            ["KIT-Fireball", "fireball", 0, [], 0],
            ["Fouineur", "fouineur", 0, [], 0],
            ["Robot Francoroute", "francoroute", 0, [], 0],
            ["Freecrawl", "freecrawl", 0, [], 0],
            ["FunnelWeb", "funnelweb", 0, [], 0],
            ["gammaSpider", "gammaSpider", 0, [], 0],
            ["gazz", "gazz", 0, [], 0],
            ["GCreep", "gcreep", 0, [], 0],
            ["GetBot", "getbot", 0, [], 0],
            ["GetURL", "geturl", 0, [], 0],
            ["Golem", "golem", 0, [], 0],
            ["Grapnel/0.01 Experiment", "grapnel", 0, [], 0],
            ["Griffon", "griffon", 0, [], 0],
            ["Gromit", "gromit", 0, [], 0],
            ["Gulper Bot", "gulperbot", 0, [], 0],
            ["HamBot", "hambot", 0, [], 0],
            ["havIndex", "havindex", 0, [], 0],
            ["Hometown Spider Pro", "hometown", 0, [], 0],
            ["HTMLgobble", "htmlgobble", 0, [], 0],
            ["Hyper-Decontextualizer", "hyperdecontextualizer", 0, [], 0],
            ["iajaBot", "iajabot", 0, [], 0],
            ["Popular Iconoclast", "iconoclast", 0, [], 0],
            ["Ingrid", "ilse", 0, [], 0],
            ["Imagelock", "imagelock", 0, [], 0],
            ["IncyWincy", "incywincy", 0, [], 0],
            ["Informant", "informant", 0, [], 0],
            ["InfoSeek Robot 1.0", "infoseek", 0, [], 0],
            ["Infoseek Sidewinder", "infoseeksidewinder", 0, [], 0],
            ["InfoSpiders", "infospider", 0, [], 0],
            ["Inspector Web", "inspectorwww", 0, [], 0],
            ["IntelliAgent", "intelliagent", 0, [], 0],
            ["Iron33", "iron33", 0, [], 0],
            ["Israeli-search", "israelisearch", 0, [], 0],
            ["JavaBee", "javabee", 0, [], 0],
            ["JBot Java Web Robot", "jbot", 0, [], 0],
            ["JCrawler", "jcrawler", 0, [], 0],
            ["JoBo Java Web Robot", "jobo", 0, [], 0],
            ["Jobot", "jobot", 0, [], 0],
            ["JoeBot", "joebot", 0, [], 0],
            ["The Jubii Indexing Robot", "jubii", 0, [], 0],
            ["JumpStation", "jumpstation", 0, [], 0],
            ["image.kapsi.net", "kapsi", 0, [], 0],
            ["Katipo", "katipo", 0, [], 0],
            ["Kilroy", "kilroy", 0, [], 0],
            ["KO_Yappo_Robot", "ko_yappo_robot", 0, [], 0],
            ["LabelGrabber", "labelgrabber\.txt", 0, [], 0],
            ["Larbin", "larbin", 0, [], 0],
            ["Legs", "legs", 0, [], 0],
            ["Link Validator", "linkidator", 0, [], 0],
            ["LinkScan", "linkscan", 0, [], 0],
            ["Lockon", "lockon", 0, [], 0],
            ["Logo.gif Crawler", "logo_gif", 0, [], 0],
            ["Mail.RU Bot", "Mail.RU_Bot", 0, [], 0],
            ["Mac WWWWorm", "macworm", 0, [], 0],
            ["Magpie", "magpie", 0, [], 0],
            ["marvin/infoseek", "marvin", 0, [], 0],
            ["Mattie", "mattie", 0, [], 0],
            ["MediaFox", "mediafox", 0, [], 0],
            ["MerzScope", "merzscope", 0, [], 0],
            ["NEC-MeshExplorer", "meshexplorer", 0, [], 0],
            ["MindCrawler", "mindcrawler", 0, [], 0],
            ["mnoGoSearch", "mnogosearch", 0, [], 0],
            ["MOMspider", "momspider", 0, [], 0],
            ["Monster", "monster", 0, [], 0],
            ["Motor", "motor", 0, [], 0],
            ["MSNBot", "msnbot", 0, [], 0],
            ["Muncher", "muncher", 0, [], 0],
            ["Mwd.Search", "mwdsearch", 0, [], 0],
            ["NDSpider", "ndspider", 0, [], 0],
            ["Nederland.zoek", "nederland\.zoek", 0, [], 0],
            ["NetCarta WebMap Engine", "netcarta", 0, [], 0],
            ["NetMechanic", "netmechanic", 0, [], 0],
            ["NetScoop", "netscoop", 0, [], 0],
            ["newscan-online", "newscan\-online", 0, [], 0],
            ["NHSE Web Forager", "nhse", 0, [], 0],
            ["The NorthStar Robot", "northstar", 0, [], 0],
            ["NZExplorer", "nzexplorer", 0, [], 0],
            ["ObjectsSearch", "objectssearch", 0, [], 0],
            ["Occam", "occam", 0, [], 0],
            ["HKU WWW Octopus", "octopus", 0, [], 0],
            ["Openfind data gatherer", "openfind", 0, [], 0],
            ["Orb Search", "orb_search", 0, [], 0],
            ["Pack Rat", "packrat", 0, [], 0],
            ["PageBoy", "pageboy", 0, [], 0],
            ["ParaSite", "parasite", 0, [], 0],
            ["Patric", "patric", 0, [], 0],
            ["Pegasus", "pegasus", 0, [], 0],
            ["The Peregrinator", "perignator", 0, [], 0],
            ["PerlCrawler 1.0", "perlcrawler", 0, [], 0],
            ["Phantom", "phantom", 0, [], 0],
            ["PhpDig", "phpdig", 0, [], 0],
            ["PiltdownMan", "piltdownman", 0, [], 0],
            ["Pimptrain.com's robot", "pimptrain", 0, [], 0],
            ["Pioneer", "pioneer", 0, [], 0],
            ["html_analyzer", "pitkow", 0, [], 0],
            ["Portal Juice Spider", "pjspider", 0, [], 0],
            ["PlumtreeWebAccessor", "plumtreewebaccessor", 0, [], 0],
            ["Poppi", "poppi", 0, [], 0],
            ["PortalB Spider", "portalb", 0, [], 0],
            ["psbot", "psbot", 0, [], 0],
            ["The Python Robot", "python", 0, [], 0],
            ["Raven Search", "raven", 0, [], 0],
            ["RBSE Spider", "rbse", 0, [], 0],
            ["Resume Robot", "resumerobot", 0, [], 0],
            ["RoadHouse Crawling System", "rhcs", 0, [], 0],
            ["Road Runner: The ImageScape Ro", "road_runner", 0, [], 0],
            ["Robbie the Robot", "robbie", 0, [], 0],
            ["ComputingSite Robi/1.0", "robi", 0, [], 0],
            ["RoboCrawl Spider", "robocrawl", 0, [], 0],
            ["RoboFox", "robofox", 0, [], 0],
            ["Robozilla", "robozilla", 0, [], 0],
            ["Roverbot", "roverbot", 0, [], 0],
            ["RuLeS", "rules", 0, [], 0],
            ["SafetyNet Robot", "safetynetrobot", 0, [], 0],
            ["Sleek", "search\-info", 0, [], 0],
            ["Search.Aus-AU.COM", "search_au", 0, [], 0],
            ["SearchProcess", "searchprocess", 0, [], 0],
            ["Senrigan", "senrigan", 0, [], 0],
            ["SG-Scout", "sgscout", 0, [], 0],
            ["ShagSeeker", "shaggy", 0, [], 0],
            ["Shai'Hulud", "shaihulud", 0, [], 0],
            ["Sift", "sift", 0, [], 0],
            ["Simmany Robot Ver1.0", "simbot", 0, [], 0],
            ["Site Valet", "site\-valet", 0, [], 0],
            ["SiteTech-Rover", "sitetech", 0, [], 0],
            ["Skymob.com", "skymob", 0, [], 0],
            ["SLCrawler", "slcrawler", 0, [], 0],
            ["Smart Spider", "smartspider", 0, [], 0],
            ["Snooper", "snooper", 0, [], 0],
            ["Solbot", "solbot", 0, [], 0],
            ["Speedy Spider", "speedy", 0, [], 0],
            ["Spider Monkey", "spider_monkey", 0, [], 0],
            ["SpiderBot", "spiderbot", 0, [], 0],
            ["Spiderline Crawler", "spiderline", 0, [], 0],
            ["SpiderMan", "spiderman", 0, [], 0],
            ["SpiderView(tm)", "spiderview", 0, [], 0],
            ["Spry Wizard Robot", "spry", 0, [], 0],
            ["Site Searcher", "ssearcher", 0, [], 0],
            ["Suke", "suke", 0, [], 0],
            ["Cliqzbot", "cliqzbot", 0, [], 0],
            ["Suntek Search Engine", "suntek", 0, [], 0],
            ["Sven", "sven", 0, [], 0],
            ["TACH Black Widow", "tach_bw", 0, [], 0],
            ["Tarantula", "tarantula", 0, [], 0],
            ["Tarspider", "tarspider", 0, [], 0],
            ["TechBOT", "techbot", 0, [], 0],
            ["Templeton", "templeton", 0, [], 0],
            ["TITAN", "titan", 0, [], 0],
            ["TitIn", "titin", 0, [], 0],
            ["The TkWWW Robot", "tkwww", 0, [], 0],
            ["TLSpider", "tlspider", 0, [], 0],
            ["UCSD Crawl", "ucsd", 0, [], 0],
            ["UdmSearch", "udmsearch", 0, [], 0],
            ["URL Check", "urlck", 0, [], 0],
            ["Valkyrie", "valkyrie", 0, [], 0],
            ["Verticrawl", "verticrawl", 0, [], 0],
            ["Victoria", "victoria", 0, [], 0],
            ["Vision-search", "visionsearch", 0, [], 0],
            ["Void-bot", "voidbot", 0, [], 0],
            ["VWbot", "vwbot", 0, [], 0],
            ["The NWI Robot", "w3index", 0, [], 0],
            ["W3M2", "w3m2", 0, [], 0],
            ["WallPaper (alias crawlpaper)", "wallpaper", 0, [], 0],
            ["the World Wide Web Wanderer", "wanderer", 0, [], 0],
            ["w@pSpider by wap4.com", "wapspider", 0, [], 0],
            ["WebBandit Web Spider", "webbandit", 0, [], 0],
            ["WebCatcher", "webcatcher", 0, [], 0],
            ["WebCopy", "webcopy", 0, [], 0],
            ["webfetcher", "webfetcher", 0, [], 0],
            ["The Webfoot Robot", "webfoot", 0, [], 0],
            ["Webinator", "webinator", 0, [], 0],
            ["WebLinker", "weblinker", 0, [], 0],
            ["WebMirror", "webmirror", 0, [], 0],
            ["The Web Moose", "webmoose", 0, [], 0],
            ["WebQuest", "webquest", 0, [], 0],
            ["Digimarc MarcSpider", "webreader", 0, [], 0],
            ["WebReaper", "webreaper", 0, [], 0],
            ["Websnarf", "websnarf", 0, [], 0],
            ["WebSpider", "webspider", 0, [], 0],
            ["WebVac", "webvac", 0, [], 0],
            ["webwalk", "webwalk", 0, [], 0],
            ["WebWalker", "webwalker", 0, [], 0],
            ["WebWatch", "webwatch", 0, [], 0],
            ["whatUseek Winona", "whatuseek", 0, [], 0],
            ["WhoWhere Robot", "whowhere", 0, [], 0],
            ["Wired Digital", "wired\-digital", 0, [], 0],
            ["w3mir", "wmir", 0, [], 0],
            ["WebStolperer", "wolp", 0, [], 0],
            ["The Web Wombat", "wombat", 0, [], 0],
            ["The World Wide Web Worm", "worm", 0, [], 0],
            ["WWWC Ver 0.2.5", "wwwc", 0, [], 0],
            ["WebZinger", "wz101", 0, [], 0],
            ["XGET", "xget", 0, [], 0],
            ["MJ12bot", "^MJ12bot", 1, [], 0],
            ["MJ12bot", "^MJ12bot.*", 1, [], 0],
            ["MJ12bot", "^MJ12bot\/v1.4.4", 1, [], 0],
            ["MJ12bot", "^MJ12bot\/v1.4.5", 1, [], 0],
            ["MJ12bot", "^MJ12bot\/v1.4.6", 1, [], 0],
            ["MJ12bot", "^MJ12bot\/v1.4.7", 1, [], 0],
            ["AESOP_com_SpiderMan", "^AESOP_com_SpiderMan", 1, [], 0],
            ["Alexibot", "^Alexibot", 1, [], 0],
            ["Anonymouse", "Anonymouse.org", 1, [], 0],
            ["asterias", "^asterias", 1, [], 0],
            ["attach", "^attach", 1, [], 0],
            ["BackDoorBot", "^BackDoorBot", 1, [], 0],
            ["BackWeb", "^BackWeb", 1, [], 0],
            ["bandit", "bandit", 1, [], 0],
            ["Baiduspider", "^Baiduspider", 1, [], 0],
            ["BatchFTP", "^BatchFTP", 1, [], 0],
            ["Bigfoot", "^Bigfoot", 1, [], 0],
            ["Black.Hole", "^Black.Hole", 1, [], 0],
            ["BlackWidow", "^BlackWidow", 1, [], 0],
            ["BlowFish", "^BlowFish", 1, [], 0],
            ["Craftbot", "^Bot\ mailto: craftbot@yahoo.com", 1, [], 0],
            ["BotALot", "^BotALot", 1, [], 0],
            ["Buddy", "Buddy", 1, [], 0],
            ["BuiltBotTough", "^BuiltBotTough", 1, [], 0],
            ["Bullseye", "^Bullseye", 1, [], 0],
            ["BunnySlippers", "^BunnySlippers", 1, [], 0],
            ["Cegbfeieh", "^Cegbfeieh", 1, [], 0],
            ["CheeseBot", "^CheeseBot", 1, [], 0],
            ["CherryPicker", "^CherryPicker", 1, [], 0],
            ["ChinaClaw", "^ChinaClaw", 1, [], 0],
            ["Collector", "Collector", 1, [], 0],
            ["Copier", "Copier", 1, [], 0],
            ["CopyRightCheck", "^CopyRightCheck", 1, [], 0],
            ["cosmos", "^cosmos", 1, [], 0],
            ["Crescent", "^Crescent", 1, [], 0],
            ["Curl", "^Curl", 1, [], 0],
            ["Custo", "^Custo", 1, [], 0],
            ["DA", "^DA", 1, [], 0],
            ["DISCo", "^DISCo", 1, [], 0],
            ["DIIbot", "^DIIbot", 1, [], 0],
            ["DittoSpyder", "^DittoSpyder", 1, [], 0],
            ["Download", "^Download", 1, [], 0],
            ["Download Demon", "^Download\ Demon", 1, [], 0],
            ["Download Devil", "^Download\ Devil", 1, [], 0],
            ["Download Wonder", "^Download\ Wonder", 1, [], 0],
            ["Downloader", "Downloader", 1, [], 0],
            ["dragonfly", "^dragonfly", 1, [], 0],
            ["Drip", "^Drip", 1, [], 0],
            ["eCatch", "^eCatch", 1, [], 0],
            ["EasyDL", "^EasyDL", 1, [], 0],
            ["ebingbong", "^ebingbong", 1, [], 0],
            ["EirGrabber", "^EirGrabber", 1, [], 0],
            ["EmailCollector", "^EmailCollector", 1, [], 0],
            ["EmailSiphon", "^EmailSiphon", 1, [], 0],
            ["EmailWolf", "^EmailWolf", 1, [], 0],
            ["EroCrawler", "^EroCrawler", 1, [], 0],
            ["Exabot", "^Exabot", 1, [], 0],
            ["Express WebPictures", "^Express\ WebPictures", 1, [], 0],
            ["Extractor", "Extractor", 1, [], 0],
            ["EyeNetIE", "^EyeNetIE", 1, [], 0],
            ["FileHound", "^FileHound", 1, [], 0],
            ["FlashGet", "^FlashGet", 1, [], 0],
            ["Foobot", "^Foobot", 1, [], 0],
            ["flunky", "^flunky", 1, [], 0],
            ["FrontPage", "^FrontPage", 1, [], 0],
            ["GetRight", "^GetRight", 1, [], 0],
            ["GetSmart", "^GetSmart", 1, [], 0],
            ["GetWeb!", "^GetWeb!", 1, [], 0],
            ["Go!Zilla", "^Go!Zilla", 1, [], 0],
            ["Google Wireless Transcoder", "Google\ Wireless\ Transcoder", 1, [], 0],
            ["Go-Ahead-Got-It", "^Go-Ahead-Got-It", 1, [], 0],
            ["gotit", "^gotit", 1, [], 0],
            ["Grabber", "Grabber", 1, [], 0],
            ["GrabNet", "^GrabNet", 1, [], 0],
            ["Grafula", "^Grafula", 1, [], 0],
            ["Harvest", "^Harvest", 1, [], 0],
            ["hloader", "^hloader", 1, [], 0],
            ["HMView", "^HMView", 1, [], 0],
            ["httplib", "^httplib", 1, [], 0],
            ["HTTrack", "^HTTrack", 1, [], 0],
            ["humanlinks", "^humanlinks", 1, [], 0],
            ["ia_archiver", "^ia_archiver", 1, [], 0],
            ["IlseBot", "^IlseBot", 1, [], 0],
            ["Image Stripper", "^Image\ Stripper", 1, [], 0],
            ["Image Sucker", "^Image\ Sucker", 1, [], 0],
            ["Indy Library", "Indy\ Library", 1, [], 0],
            ["InfoNaviRobot", "^InfoNaviRobot", 1, [], 0],
            ["InfoTekies", "^InfoTekies", 1, [], 0],
            ["Intelliseek", "^Intelliseek", 1, [], 0],
            ["InterGET", "^InterGET", 1, [], 0],
            ["Internet Ninja", "^Internet\ Ninja", 1, [], 0],
            ["Iria", "^Iria", 1, [], 0],
            ["Jakarta", "^Jakarta", 1, [], 0],
            ["JennyBot", "^JennyBot", 1, [], 0],
            ["JetCar", "^JetCar", 1, [], 0],
            ["JOC", "^JOC", 1, [], 0],
            ["JustView", "^JustView", 1, [], 0],
            ["Jyxobot", "^Jyxobot", 1, [], 0],
            ["Kenjin.Spider", "^Kenjin.Spider", 1, [], 0],
            ["Keyword.Density", "^Keyword.Density", 1, [], 0],
            ["larbin", "^larbin", 1, [], 0],
            ["LeechFTP", "^LeechFTP", 1, [], 0],
            ["LexiBot", "^LexiBot", 1, [], 0],
            ["lftp", "^lftp", 1, [], 0],
            ["libWeb/clsHTTP", "^libWeb/clsHTTP", 1, [], 0],
            ["likse", "^likse", 1, [], 0],
            ["LinkextractorPro", "^LinkextractorPro", 1, [], 0],
            ["LinkScan/8.1a.Unix", "^LinkScan/8.1a.Unix", 1, [], 0],
            ["LNSpiderguyt", "^LNSpiderguyt", 1, [], 0],
            ["LinkWalker", "^LinkWalker", 1, [], 0],
            ["lwp-trivial", "^lwp-trivial", 1, [], 0],
            ["LWP::Simple", "^LWP::Simple", 1, [], 0],
            ["Magnet", "^Magnet", 1, [], 0],
            ["Mag-Net", "^Mag-Net", 1, [], 0],
            ["MarkWatch", "^MarkWatch", 1, [], 0],
            ["Mass Downloader", "^Mass\ Downloader", 1, [], 0],
            ["Mata.Hari", "^Mata.Hari", 1, [], 0],
            ["Memo", "^Memo", 1, [], 0],
            ["Microsoft.URL", "^Microsoft.URL", 1, [], 0],
            ["Microsoft URL Control", "^Microsoft\ URL\ Control", 1, [], 0],
            ["MIDown tool", "^MIDown\ tool", 1, [], 0],
            ["MIIxpc", "^MIIxpc", 1, [], 0],
            ["Mirror", "^Mirror", 1, [], 0],
            ["Missigua Locator", "^Missigua\ Locator", 1, [], 0],
            ["Mister PiX", "^Mister\ PiX", 1, [], 0],
            ["moget", "^moget", 1, [], 0],
            ["Mozilla/3.Mozilla", "^Mozilla/3.Mozilla/2.01", 1, [], 0],
            ["Mozilla.*NEWT", "^Mozilla.*NEWT", 1, [], 0],
            ["NAMEPROTECT", "^NAMEPROTECT", 1, [], 0],
            ["Navroad", "^Navroad", 1, [], 0],
            ["NearSite", "^NearSite", 1, [], 0],
            ["NetAnts", "^NetAnts", 1, [], 0],
            ["Netcraft", "^Netcraft", 1, [], 0],
            ["NetMechanic", "^NetMechanic", 1, [], 0],
            ["NetSpider", "^NetSpider", 1, [], 0],
            ["Net Vampire", "^Net\ Vampire", 1, [], 0],
            ["NetZIP", "^NetZIP", 1, [], 0],
            ["NextGenSearchBot", "^NextGenSearchBot", 1, [], 0],
            ["NG", "^NG", 1, [], 0],
            ["NICErsPRO", "^NICErsPRO", 1, [], 0],
            ["NimbleCrawler", "^NimbleCrawler", 1, [], 0],
            ["Ninja", "^Ninja", 1, [], 0],
            ["NPbot", "^NPbot", 1, [], 0],
            ["Octopus", "^Octopus", 1, [], 0],
            ["Offline Explorer", "^Offline\ Explorer", 1, [], 0],
            ["Offline Navigator", "^Offline\ Navigator", 1, [], 0],
            ["Openfind", "^Openfind", 1, [], 0],
            ["OutfoxBot", "^OutfoxBot", 1, [], 0],
            ["PageGrabber", "^PageGrabber", 1, [], 0],
            ["Papa Foto", "^Papa\ Foto", 1, [], 0],
            ["pavuk", "^pavuk", 1, [], 0],
            ["pcBrowser", "^pcBrowser", 1, [], 0],
            ["PHP version tracker", "^PHP\ version\ tracker", 1, [], 0],
            ["Pockey", "^Pockey", 1, [], 0],
            ["ProPowerBot", "^ProPowerBot/2.14", 1, [], 0],
            ["ProWebWalker", "^ProWebWalker", 1, [], 0],
            ["psbot", "^psbot", 1, [], 0],
            ["Pump", "^Pump", 1, [], 0],
            ["QueryN.Metasearch", "^QueryN.Metasearch", 1, [], 0],
            ["RealDownload", "^RealDownload", 1, [], 0],
            ["Reaper", "Reaper", 1, [], 0],
            ["Recorder", "Recorder", 1, [], 0],
            ["ReGet", "^ReGet", 1, [], 0],
            ["RepoMonkey", "^RepoMonkey", 1, [], 0],
            ["RMA", "^RMA", 1, [], 0],
            ["Siphon", "Siphon", 1, [], 0],
            ["sitecheck.internetseer.com", "sitecheck.internetseer.com", 1, [], 0],
            ["SiteSnagger", "^SiteSnagger", 1, [], 0],
            ["SlySearch", "^SlySearch", 1, [], 0],
            ["SmartDownload", "^SmartDownload", 1, [], 0],
            ["Snake", "^Snake", 1, [], 0],
            ["Snapbot", "^Snapbot", 1, [], 0],
            ["Snoopy", "^Snoopy", 1, [], 0],
            ["sogou", "^sogou", 1, [], 0],
            ["SpaceBison", "^SpaceBison", 1, [], 0],
            ["SpankBot", "^SpankBot", 1, [], 0],
            ["spanner", "^spanner", 1, [], 0],
            ["Sqworm", "^Sqworm", 1, [], 0],
            ["Stripper", "Stripper", 1, [], 0],
            ["Sucker", "Sucker", 1, [], 0],
            ["SuperBot", "^SuperBot", 1, [], 0],
            ["SuperHTTP", "^SuperHTTP", 1, [], 0],
            ["Surfbot", "^Surfbot", 1, [], 0],
            ["suzuran", "^suzuran", 1, [], 0],
            ["Szukacz", "^Szukacz/1.4", 1, [], 0],
            ["tAkeOut", "^tAkeOut", 1, [], 0],
            ["Teleport", "^Teleport", 1, [], 0],
            ["Telesoft", "^Telesoft", 1, [], 0],
            ["TurnitinBot", "^TurnitinBot/1.5", 1, [], 0],
            ["The.Intraformant", "^The.Intraformant", 1, [], 0],
            ["TheNomad", "^TheNomad", 1, [], 0],
            ["TightTwatBot", "^TightTwatBot", 1, [], 0],
            ["Titan", "^Titan", 1, [], 0],
            ["toCrawl/UrlDispatcher", "^toCrawl/UrlDispatcher", 1, [], 0],
            ["True_Robot", "^True_Robot", 1, [], 0],
            ["turingos", "^turingos", 1, [], 0],
            ["TurnitinBot", "^TurnitinBot", 1, [], 0],
            ["URLy.Warning", "^URLy.Warning", 1, [], 0],
            ["Vacuum", "^Vacuum", 1, [], 0],
            ["VCI", "^VCI", 1, [], 0],
            ["VoidEYE", "^VoidEYE", 1, [], 0],
            ["Web Image Collector", "^Web\ Image\ Collector", 1, [], 0],
            ["Web Sucker", "^Web\ Sucker", 1, [], 0],
            ["WebAuto", "^WebAuto", 1, [], 0],
            ["Webbandit", "^Webbandit", 1, [], 0],
            ["Webclipping.com", "^Webclipping.com", 1, [], 0],
            ["WebCopier", "^WebCopier", 1, [], 0],
            ["WebEMailExtrac.*", "^WebEMailExtrac.*", 1, [], 0],
            ["WebEnhancer", "^WebEnhancer", 1, [], 0],
            ["WebFetch", "^WebFetch", 1, [], 0],
            ["WebGo IS", "^WebGo\ IS", 1, [], 0],
            ["Web.Image.Collector", "^Web.Image.Collector", 1, [], 0],
            ["WebLeacher", "^WebLeacher", 1, [], 0],
            ["WebmasterWorldForumBot", "^WebmasterWorldForumBot", 1, [], 0],
            ["WebReaper", "^WebReaper", 1, [], 0],
            ["WebSauger", "^WebSauger", 1, [], 0],
            ["WebSite", "^WebSite", 1, [], 0],
            ["Website eXtractor", "^Website\ eXtractor", 1, [], 0],
            ["Website Quester", "^Website\ Quester", 1, [], 0],
            ["Webster", "^Webster", 1, [], 0],
            ["WebStripper", "^WebStripper", 1, [], 0],
            ["WebWhacker", "^WebWhacker", 1, [], 0],
            ["WebZIP", "^WebZIP", 1, [], 0],
            ["Whacker", "Whacker", 1, [], 0],
            ["Widow", "^Widow", 1, [], 0],
            ["WISENutbot", "^WISENutbot", 1, [], 0],
            ["WWWOFFLE", "^WWWOFFLE", 1, [], 0],
            ["WWW-Collector-E", "^WWW-Collector-E", 1, [], 0],
            ["Xaldon", "^Xaldon", 1, [], 0],
            ["Xenu", "^Xenu", 1, [], 0],
            ["Zeus", "^Zeus", 1, [], 0],
            ["Zyborg", "^Zyborg", 1, [], 0],
            ["Lipperhey", "lipperhey", 0, ["lipperhey.com", "*.lipperhey.com"], 0],
            ["Dataprovider", "Dataprovider\.com", 0, ["dataprovider.com", "*.dataprovider.com"], 0],
        ];
        foreach ($rows as &$row) {
            if(is_array($row[3]))
                $row[3] = serialize($row[3]);
        }
        $this->batchInsert('{{%stats_robots}}', ['name', 'regexp', 'is_badbot', 'hosts', 'type'], $rows);

    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {

        if (!(Yii::$app->db->getTableSchema('{{%stats_visitors}}', true) === null)) {
            $this->dropForeignKey(
                'fk_visitors_to_robots',
                '{{%stats_visitors}}'
            );
        }

        $this->truncateTable('{{%stats_robots}}');
        $this->dropTable('{{%stats_robots}}');
    }
}