<?php

use yii\db\Migration;
use yii\base\InvalidConfigException;
use yii\rbac\DbManager;

/**
 * Class m190209_224417_stats_robots
 */
class m190209_224417_stats_robots extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $tableOptions = null;
        if ($this->db->driverName === 'mysql') {
            $tableOptions = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB';
        }

        $this->createTable('{{%stats_robots}}', [
            'id'=> $this->primaryKey(11),
            'name' => $this->string(32)->notNull(),
            'regexp' => $this->string(32)->notNull(),
            'is_badbot' => $this->boolean()->defaultValue(false),
        ], $tableOptions);

        if (!(Yii::$app->db->getTableSchema('{{%stats_visitors}}', true) === null)) {
            $this->addForeignKey(
                'fk_visitors_to_robots',
                '{{%stats_visitors}}',
                'robot_id',
                '{{%stats_robots}}',
                'id',
                'NO ACTION',
                'CASCADE'
            );
        }

        $rows = [
            ["Rambler", "rambler", "0"],
            ["GoogleBot", "googlebot", "0"],
            ["Aport", "aport", "0"],
            ["Yahoo", "yahoo", "0"],
            ["MSNbot", "msnbot", "0"],
            ["Turtle", "turtle", "0"],
            ["Mail.Ru", "mail.ru", "0"],
            ["Omsktele", "omsktele", "0"],
            ["YetiBot", "yetibot", "0"],
            ["PicSearch", "picsearch", "0"],
            ["Sape.Bot", "sape.bot", "0"],
            ["Sape_context", "sape_context", "0"],
            ["Gigabot", "gigabot", "0"],
            ["Snapbot", "snapbot", "0"],
            ["Alexa.com", "alexa.com", "0"],
            ["Megadownload.net", "megadownload.net", "0"],
            ["Askpeter.info", "askpeter.info", "0"],
            ["Igde.ru", "igde.ru", "0"],
            ["Ask.com", "ask.com", "0"],
            ["Qwartabot", "qwartabot", "0"],
            ["Yanga.co.uk", "yanga.co.uk", "0"],
            ["Scoutjet", "scoutjet", "0"],
            ["Similarpages", "similarpages", "0"],
            ["OozBot", "oozbot", "0"],
            ["Shrinktheweb.com", "shrinktheweb.com", "0"],
            ["Aboutusbot", "aboutusbot", "0"],
            ["Followsite.com", "followsite.com", "0"],
            ["Dataparksearch", "dataparksearch", "0"],
            ["Google Sitemaps", "google-sitemaps", "0"],
            ["Google appEngine", "appEngine-google", "0"],
            ["Google feedFetcher", "feedfetcher-google", "0"],
            ["Liveinternet.ru", "liveinternet.ru", "0"],
            ["Xml-Sitemaps.com", "xml-sitemaps.com", "0"],
            ["Agama", "agama", "0"],
            ["Metadatalabs.com", "metadatalabs.com", "0"],
            ["h1.hrn.ru", "h1.hrn.ru", "0"],
            ["Googlealert.com", "googlealert.com", "0"],
            ["Seo-Rus.com", "seo-rus.com", "0"],
            ["YadirectBot", "yaDirectBot", "0"],
            ["Yandeg", "yandeG", "0"],
            ["Yandex", "yandex", "0"],
            ["YandexSomething", "yandexSomething", "0"],
            ["Copyscape.com", "Copyscape.com", "0"],
            ["Adsbot-Google", "AdsBot-Google", "0"],
            ["Domaintools.com", "domaintools.com", "0"],
            ["Nigma.ru", "Nigma.ru", "0"],
            ["Bing.com", "bing.com", "0"],
            ["Dotnetdotcom", "dotnetdotcom", "0"],
            ["Aport", "aport", "0"],
            ["AWBot", "awbot", "0"],
            ["BaiDuSpider", "baiduspider", "0"],
            ["Bobby", "bobby", "0"],
            ["Boris", "boris", "0"],
            ["Bumblebee (relevare.com)", "bumblebee", "0"],
            ["CsCrawler", "cscrawler", "0"],
            ["DaviesBot", "daviesbot", "0"],
            ["ExactSeek Crawler", "exactseek", "0"],
            ["Ezresult", "ezresult", "0"],
            ["GigaBot", "gigabot", "0"],
            ["GNOD Spider", "gnodspider", "0"],
            ["Grub.org", "grub", "0"],
            ["Mirago", "henrythemiragorobot", "0"],
            ["Holmes", "holmes", "0"],
            ["InternetSeer", "internetseer", "0"],
            ["JustView", "justview", "0"],
            ["LinkBot", "linkbot", "0"],
            ["MetaGer LinkChecker", "metager\-linkchecker", "0"],
            ["LinkChecker", "linkchecker", "0"],
            ["Microsoft URL Control", "microsoft_url_control", "0"],
            ["MSIECrawler", "msiecrawler", "0"],
            ["Nagios", "nagios", "0"],
            ["Perman surfer", "perman", "0"],
            ["Pompos", "pompos", "0"],
            ["StackRambler", "rambler", "0"],
            ["Red Alert", "redalert", "0"],
            ["Shoutcast Directory Service", "shoutcast", "0"],
            ["SlySearch", "slysearch", "0"],
            ["SurveyBot", "surveybot", "0"],
            ["Turn It In", "turnitinbot", "0"],
            ["Turtle", "turtlescanner", "0"],
            ["Turtle", "turtle", "0"],
            ["Ultraseek", "ultraseek", "0"],
            ["WebClipping.com", "webclipping\.com", "0"],
            ["webcompass", "webcompass", "0"],
            ["Web Wombat Redback Spider", "wonderer", "0"],
            ["Yahoo Vertical Crawler", "yahoo\-verticalcrawler", "0"],
            ["Yandex bot", "yandex", "0"],
            ["ZealBot", "zealbot", "0"],
            ["Zyborg", "zyborg", "0"],
            ["Walhello appie", "appie", "0"],
            ["ArchitextSpider", "architext", "0"],
            ["AskJeeves", "jeeves", "0"],
            ["Bjaaland", "bjaaland", "0"],
            ["Googlebot", "googlebot", "0"],
            ["Northern Light Gulliver", "gulliver", "0"],
            ["Harvest", "harvest", "0"],
            ["ht://Dig", "htdig", "0"],
            ["LinkWalker", "linkwalker", "0"],
            ["Lycos", "lycos_", "0"],
            ["moget", "moget", "0"],
            ["Muscat Ferret", "muscatferret", "0"],
            ["Internet Shinchakubin", "myweb", "0"],
            ["Nomad", "nomad", "0"],
            ["Scooter", "scooter", "0"],
            ["Inktomi Slurp", "slurp", "0"],
            ["Voyager", "^voyager\/", "0"],
            ["weblayers", "weblayers", "0"],
            ["Antibot", "antibot", "0"],
            ["Digout4u", "digout4u", "0"],
            ["EchO!", "echo", "0"],
            ["Fast-Webcrawler", "fast\-webcrawler", "0"],
            ["Alexa (IA Archiver)", "ia_archiver", "0"],
            ["JennyBot", "jennybot", "0"],
            ["Mercator", "mercator", "0"],
            ["Netcraft", "netcraft", "0"],
            ["Petersnews", "petersnews", "0"],
            ["Unlost Web Crawler", "unlost_web_crawler", "0"],
            ["Voila", "voila", "0"],
            ["WebBase", "webbase", "0"],
            ["WISENutbot", "wisenutbot", "0"],
            ["Fish search", "[^a]fish", "0"],
            ["ABCdatos BotLink", "abcdatos", "0"],
            ["Acme.Spider", "acme\.spider", "0"],
            ["Ahoy! The Homepage Finder", "ahoythehomepagefinder", "0"],
            ["Alkaline", "alkaline", "0"],
            ["Anthill", "anthill", "0"],
            ["Arachnophilia", "arachnophilia", "0"],
            ["Arale", "arale", "0"],
            ["Araneo", "araneo", "0"],
            ["Aretha", "aretha", "0"],
            ["ARIADNE", "ariadne", "0"],
            ["arks", "arks", "0"],
            ["ASpider (Associative Spider)", "aspider", "0"],
            ["ATN Worldwide", "atn\.txt", "0"],
            ["Atomz.com Search Robot", "atomz", "0"],
            ["AURESYS", "auresys", "0"],
            ["BackRub", "backrub", "0"],
            ["BBot", "bbot", "0"],
            ["Big Brother", "bigbrother", "0"],
            ["BlackWidow", "blackwidow", "0"],
            ["Die Blinde Kuh", "blindekuh", "0"],
            ["Bloodhound", "bloodhound", "0"],
            ["Borg-Bot", "borg\-bot", "0"],
            ["bright.net caching robot", "brightnet", "0"],
            ["BSpider", "bspider", "0"],
            ["CACTVS Chemistry Spider", "cactvschemistryspider", "0"],
            ["Calif", "calif[^r]", "0"],
            ["Cassandra", "cassandra", "0"],
            ["Digimarc Marcspider/CGI", "cgireader", "0"],
            ["Checkbot", "checkbot", "0"],
            ["ChristCrawler.com", "christcrawler", "0"],
            ["churl", "churl", "0"],
            ["cIeNcIaFiCcIoN.nEt", "cienciaficcion", "0"],
            ["Collective", "collective", "0"],
            ["Combine System", "combine", "0"],
            ["Conceptbot", "conceptbot", "0"],
            ["CoolBot", "coolbot", "0"],
            ["Web Core / Roots", "core", "0"],
            ["XYLEME Robot", "cosmos", "0"],
            ["Internet Cruiser Robot", "cruiser", "0"],
            ["Cusco", "cusco", "0"],
            ["CyberSpyder Link Test", "cyberspyder", "0"],
            ["Desert Realm Spider", "desertrealm", "0"],
            ["DeWeb(c) Katalog/Index", "deweb", "0"],
            ["DienstSpider", "dienstspider", "0"],
            ["Digger", "digger", "0"],
            ["Digital Integrity Robot", "diibot", "0"],
            ["Direct Hit Grabber", "direct_hit", "0"],
            ["DNAbot", "dnabot", "0"],
            ["DownLoad Express", "download_express", "0"],
            ["DragonBot", "dragonbot", "0"],
            ["DWCP (Dridus' Web Cataloging P", "dwcp", "0"],
            ["e-collector", "e\-collector", "0"],
            ["EbiNess", "ebiness", "0"],
            ["ELFINBOT", "elfinbot", "0"],
            ["Emacs-w3 Search Engine", "emacs", "0"],
            ["ananzi", "emcspider", "0"],
            ["Esther", "esther", "0"],
            ["Evliya Celebi", "evliyacelebi", "0"],
            ["FastCrawler", "fastcrawler", "0"],
            ["Fluid Dynamics Search Engine r", "fdse", "0"],
            ["Felix IDE", "felix", "0"],
            ["FetchRover", "fetchrover", "0"],
            ["Femtosearch", "FemtosearchBot", "0"],
            ["Fido", "fido", "0"],
            ["Finnish", "finnish", "0"],
            ["KIT-Fireball", "fireball", "0"],
            ["Fouineur", "fouineur", "0"],
            ["Robot Francoroute", "francoroute", "0"],
            ["Freecrawl", "freecrawl", "0"],
            ["FunnelWeb", "funnelweb", "0"],
            ["gammaSpider", "gammaSpider", "0"],
            ["gazz", "gazz", "0"],
            ["GCreep", "gcreep", "0"],
            ["GetBot", "getbot", "0"],
            ["GetURL", "geturl", "0"],
            ["Golem", "golem", "0"],
            ["Grapnel/0.01 Experiment", "grapnel", "0"],
            ["Griffon", "griffon", "0"],
            ["Gromit", "gromit", "0"],
            ["Gulper Bot", "gulperbot", "0"],
            ["HamBot", "hambot", "0"],
            ["havIndex", "havindex", "0"],
            ["Hometown Spider Pro", "hometown", "0"],
            ["HTMLgobble", "htmlgobble", "0"],
            ["Hyper-Decontextualizer", "hyperdecontextualizer", "0"],
            ["iajaBot", "iajabot", "0"],
            ["Popular Iconoclast", "iconoclast", "0"],
            ["Ingrid", "ilse", "0"],
            ["Imagelock", "imagelock", "0"],
            ["IncyWincy", "incywincy", "0"],
            ["Informant", "informant", "0"],
            ["InfoSeek Robot 1.0", "infoseek", "0"],
            ["Infoseek Sidewinder", "infoseeksidewinder", "0"],
            ["InfoSpiders", "infospider", "0"],
            ["Inspector Web", "inspectorwww", "0"],
            ["IntelliAgent", "intelliagent", "0"],
            ["Iron33", "iron33", "0"],
            ["Israeli-search", "israelisearch", "0"],
            ["JavaBee", "javabee", "0"],
            ["JBot Java Web Robot", "jbot", "0"],
            ["JCrawler", "jcrawler", "0"],
            ["JoBo Java Web Robot", "jobo", "0"],
            ["Jobot", "jobot", "0"],
            ["JoeBot", "joebot", "0"],
            ["The Jubii Indexing Robot", "jubii", "0"],
            ["JumpStation", "jumpstation", "0"],
            ["image.kapsi.net", "kapsi", "0"],
            ["Katipo", "katipo", "0"],
            ["Kilroy", "kilroy", "0"],
            ["KO_Yappo_Robot", "ko_yappo_robot", "0"],
            ["LabelGrabber", "labelgrabber\.txt", "0"],
            ["Larbin", "larbin", "0"],
            ["Legs", "legs", "0"],
            ["Link Validator", "linkidator", "0"],
            ["LinkScan", "linkscan", "0"],
            ["Lockon", "lockon", "0"],
            ["Logo.gif Crawler", "logo_gif", "0"],
            ["Mac WWWWorm", "macworm", "0"],
            ["Magpie", "magpie", "0"],
            ["marvin/infoseek", "marvin", "0"],
            ["Mattie", "mattie", "0"],
            ["MediaFox", "mediafox", "0"],
            ["MerzScope", "merzscope", "0"],
            ["NEC-MeshExplorer", "meshexplorer", "0"],
            ["MindCrawler", "mindcrawler", "0"],
            ["mnoGoSearch", "mnogosearch", "0"],
            ["MOMspider", "momspider", "0"],
            ["Monster", "monster", "0"],
            ["Motor", "motor", "0"],
            ["MSNBot", "msnbot", "0"],
            ["Muncher", "muncher", "0"],
            ["Mwd.Search", "mwdsearch", "0"],
            ["NDSpider", "ndspider", "0"],
            ["Nederland.zoek", "nederland\.zoek", "0"],
            ["NetCarta WebMap Engine", "netcarta", "0"],
            ["NetMechanic", "netmechanic", "0"],
            ["NetScoop", "netscoop", "0"],
            ["newscan-online", "newscan\-online", "0"],
            ["NHSE Web Forager", "nhse", "0"],
            ["The NorthStar Robot", "northstar", "0"],
            ["NZExplorer", "nzexplorer", "0"],
            ["ObjectsSearch", "objectssearch", "0"],
            ["Occam", "occam", "0"],
            ["HKU WWW Octopus", "octopus", "0"],
            ["Openfind data gatherer", "openfind", "0"],
            ["Orb Search", "orb_search", "0"],
            ["Pack Rat", "packrat", "0"],
            ["PageBoy", "pageboy", "0"],
            ["ParaSite", "parasite", "0"],
            ["Patric", "patric", "0"],
            ["Pegasus", "pegasus", "0"],
            ["The Peregrinator", "perignator", "0"],
            ["PerlCrawler 1.0", "perlcrawler", "0"],
            ["Phantom", "phantom", "0"],
            ["PhpDig", "phpdig", "0"],
            ["PiltdownMan", "piltdownman", "0"],
            ["Pimptrain.com's robot", "pimptrain", "0"],
            ["Pioneer", "pioneer", "0"],
            ["html_analyzer", "pitkow", "0"],
            ["Portal Juice Spider", "pjspider", "0"],
            ["PlumtreeWebAccessor", "plumtreewebaccessor", "0"],
            ["Poppi", "poppi", "0"],
            ["PortalB Spider", "portalb", "0"],
            ["psbot", "psbot", "0"],
            ["The Python Robot", "python", "0"],
            ["Raven Search", "raven", "0"],
            ["RBSE Spider", "rbse", "0"],
            ["Resume Robot", "resumerobot", "0"],
            ["RoadHouse Crawling System", "rhcs", "0"],
            ["Road Runner: The ImageScape Ro", "road_runner", "0"],
            ["Robbie the Robot", "robbie", "0"],
            ["ComputingSite Robi/1.0", "robi", "0"],
            ["RoboCrawl Spider", "robocrawl", "0"],
            ["RoboFox", "robofox", "0"],
            ["Robozilla", "robozilla", "0"],
            ["Roverbot", "roverbot", "0"],
            ["RuLeS", "rules", "0"],
            ["SafetyNet Robot", "safetynetrobot", "0"],
            ["Sleek", "search\-info", "0"],
            ["Search.Aus-AU.COM", "search_au", "0"],
            ["SearchProcess", "searchprocess", "0"],
            ["Senrigan", "senrigan", "0"],
            ["SG-Scout", "sgscout", "0"],
            ["ShagSeeker", "shaggy", "0"],
            ["Shai'Hulud", "shaihulud", "0"],
            ["Sift", "sift", "0"],
            ["Simmany Robot Ver1.0", "simbot", "0"],
            ["Site Valet", "site\-valet", "0"],
            ["SiteTech-Rover", "sitetech", "0"],
            ["Skymob.com", "skymob", "0"],
            ["SLCrawler", "slcrawler", "0"],
            ["Smart Spider", "smartspider", "0"],
            ["Snooper", "snooper", "0"],
            ["Solbot", "solbot", "0"],
            ["Speedy Spider", "speedy", "0"],
            ["Spider Monkey", "spider_monkey", "0"],
            ["SpiderBot", "spiderbot", "0"],
            ["Spiderline Crawler", "spiderline", "0"],
            ["SpiderMan", "spiderman", "0"],
            ["SpiderView(tm)", "spiderview", "0"],
            ["Spry Wizard Robot", "spry", "0"],
            ["Site Searcher", "ssearcher", "0"],
            ["Suke", "suke", "0"],
            ["Cliqzbot", "cliqzbot", "0"],
            ["Suntek Search Engine", "suntek", "0"],
            ["Sven", "sven", "0"],
            ["TACH Black Widow", "tach_bw", "0"],
            ["Tarantula", "tarantula", "0"],
            ["Tarspider", "tarspider", "0"],
            ["TechBOT", "techbot", "0"],
            ["Templeton", "templeton", "0"],
            ["TITAN", "titan", "0"],
            ["TitIn", "titin", "0"],
            ["The TkWWW Robot", "tkwww", "0"],
            ["TLSpider", "tlspider", "0"],
            ["UCSD Crawl", "ucsd", "0"],
            ["UdmSearch", "udmsearch", "0"],
            ["URL Check", "urlck", "0"],
            ["Valkyrie", "valkyrie", "0"],
            ["Verticrawl", "verticrawl", "0"],
            ["Victoria", "victoria", "0"],
            ["Vision-search", "visionsearch", "0"],
            ["Void-bot", "voidbot", "0"],
            ["VWbot", "vwbot", "0"],
            ["The NWI Robot", "w3index", "0"],
            ["W3M2", "w3m2", "0"],
            ["WallPaper (alias crawlpaper)", "wallpaper", "0"],
            ["the World Wide Web Wanderer", "wanderer", "0"],
            ["w@pSpider by wap4.com", "wapspider", "0"],
            ["WebBandit Web Spider", "webbandit", "0"],
            ["WebCatcher", "webcatcher", "0"],
            ["WebCopy", "webcopy", "0"],
            ["webfetcher", "webfetcher", "0"],
            ["The Webfoot Robot", "webfoot", "0"],
            ["Webinator", "webinator", "0"],
            ["WebLinker", "weblinker", "0"],
            ["WebMirror", "webmirror", "0"],
            ["The Web Moose", "webmoose", "0"],
            ["WebQuest", "webquest", "0"],
            ["Digimarc MarcSpider", "webreader", "0"],
            ["WebReaper", "webreaper", "0"],
            ["Websnarf", "websnarf", "0"],
            ["WebSpider", "webspider", "0"],
            ["WebVac", "webvac", "0"],
            ["webwalk", "webwalk", "0"],
            ["WebWalker", "webwalker", "0"],
            ["WebWatch", "webwatch", "0"],
            ["whatUseek Winona", "whatuseek", "0"],
            ["WhoWhere Robot", "whowhere", "0"],
            ["Wired Digital", "wired\-digital", "0"],
            ["w3mir", "wmir", "0"],
            ["WebStolperer", "wolp", "0"],
            ["The Web Wombat", "wombat", "0"],
            ["The World Wide Web Worm", "worm", "0"],
            ["WWWC Ver 0.2.5", "wwwc", "0"],
            ["WebZinger", "wz101", "0"],
            ["XGET", "xget", "0"],
            ["MJ12bot", "^MJ12bot", "1"],
            ["MJ12bot", "^MJ12bot.*", "1"],
            ["MJ12bot", "^MJ12bot\/v1.4.4", "1"],
            ["MJ12bot", "^MJ12bot\/v1.4.5", "1"],
            ["MJ12bot", "^MJ12bot\/v1.4.6", "1"],
            ["MJ12bot", "^MJ12bot\/v1.4.7", "1"],
            ["AESOP_com_SpiderMan", "^AESOP_com_SpiderMan", "1"],
            ["Alexibot", "^Alexibot", "1"],
            ["Anonymouse", "Anonymouse.org", "1"],
            ["asterias", "^asterias", "1"],
            ["attach", "^attach", "1"],
            ["BackDoorBot", "^BackDoorBot", "1"],
            ["BackWeb", "^BackWeb", "1"],
            ["bandit", "bandit", "1"],
            ["Baiduspider", "^Baiduspider", "1"],
            ["BatchFTP", "^BatchFTP", "1"],
            ["Bigfoot", "^Bigfoot", "1"],
            ["Black.Hole", "^Black.Hole", "1"],
            ["BlackWidow", "^BlackWidow", "1"],
            ["BlowFish", "^BlowFish", "1"],
            ["Craftbot", "^Bot\ mailto: craftbot@yahoo.com", "1"],
            ["BotALot", "^BotALot", "1"],
            ["Buddy", "Buddy", "1"],
            ["BuiltBotTough", "^BuiltBotTough", "1"],
            ["Bullseye", "^Bullseye", "1"],
            ["BunnySlippers", "^BunnySlippers", "1"],
            ["Cegbfeieh", "^Cegbfeieh", "1"],
            ["CheeseBot", "^CheeseBot", "1"],
            ["CherryPicker", "^CherryPicker", "1"],
            ["ChinaClaw", "^ChinaClaw", "1"],
            ["Collector", "Collector", "1"],
            ["Copier", "Copier", "1"],
            ["CopyRightCheck", "^CopyRightCheck", "1"],
            ["cosmos", "^cosmos", "1"],
            ["Crescent", "^Crescent", "1"],
            ["Curl", "^Curl", "1"],
            ["Custo", "^Custo", "1"],
            ["DA", "^DA", "1"],
            ["DISCo", "^DISCo", "1"],
            ["DIIbot", "^DIIbot", "1"],
            ["DittoSpyder", "^DittoSpyder", "1"],
            ["Download", "^Download", "1"],
            ["Download Demon", "^Download\ Demon", "1"],
            ["Download Devil", "^Download\ Devil", "1"],
            ["Download Wonder", "^Download\ Wonder", "1"],
            ["Downloader", "Downloader", "1"],
            ["dragonfly", "^dragonfly", "1"],
            ["Drip", "^Drip", "1"],
            ["eCatch", "^eCatch", "1"],
            ["EasyDL", "^EasyDL", "1"],
            ["ebingbong", "^ebingbong", "1"],
            ["EirGrabber", "^EirGrabber", "1"],
            ["EmailCollector", "^EmailCollector", "1"],
            ["EmailSiphon", "^EmailSiphon", "1"],
            ["EmailWolf", "^EmailWolf", "1"],
            ["EroCrawler", "^EroCrawler", "1"],
            ["Exabot", "^Exabot", "1"],
            ["Express WebPictures", "^Express\ WebPictures", "1"],
            ["Extractor", "Extractor", "1"],
            ["EyeNetIE", "^EyeNetIE", "1"],
            ["FileHound", "^FileHound", "1"],
            ["FlashGet", "^FlashGet", "1"],
            ["Foobot", "^Foobot", "1"],
            ["flunky", "^flunky", "1"],
            ["FrontPage", "^FrontPage", "1"],
            ["GetRight", "^GetRight", "1"],
            ["GetSmart", "^GetSmart", "1"],
            ["GetWeb!", "^GetWeb!", "1"],
            ["Go!Zilla", "^Go!Zilla", "1"],
            ["Google Wireless Transcoder", "Google\ Wireless\ Transcoder", "1"],
            ["Go-Ahead-Got-It", "^Go-Ahead-Got-It", "1"],
            ["gotit", "^gotit", "1"],
            ["Grabber", "Grabber", "1"],
            ["GrabNet", "^GrabNet", "1"],
            ["Grafula", "^Grafula", "1"],
            ["Harvest", "^Harvest", "1"],
            ["hloader", "^hloader", "1"],
            ["HMView", "^HMView", "1"],
            ["httplib", "^httplib", "1"],
            ["HTTrack", "^HTTrack", "1"],
            ["humanlinks", "^humanlinks", "1"],
            ["ia_archiver", "^ia_archiver", "1"],
            ["IlseBot", "^IlseBot", "1"],
            ["Image Stripper", "^Image\ Stripper", "1"],
            ["Image Sucker", "^Image\ Sucker", "1"],
            ["Indy Library", "Indy\ Library", "1"],
            ["InfoNaviRobot", "^InfoNaviRobot", "1"],
            ["InfoTekies", "^InfoTekies", "1"],
            ["Intelliseek", "^Intelliseek", "1"],
            ["InterGET", "^InterGET", "1"],
            ["Internet Ninja", "^Internet\ Ninja", "1"],
            ["Iria", "^Iria", "1"],
            ["Jakarta", "^Jakarta", "1"],
            ["JennyBot", "^JennyBot", "1"],
            ["JetCar", "^JetCar", "1"],
            ["JOC", "^JOC", "1"],
            ["JustView", "^JustView", "1"],
            ["Jyxobot", "^Jyxobot", "1"],
            ["Kenjin.Spider", "^Kenjin.Spider", "1"],
            ["Keyword.Density", "^Keyword.Density", "1"],
            ["larbin", "^larbin", "1"],
            ["LeechFTP", "^LeechFTP", "1"],
            ["LexiBot", "^LexiBot", "1"],
            ["lftp", "^lftp", "1"],
            ["libWeb/clsHTTP", "^libWeb/clsHTTP", "1"],
            ["likse", "^likse", "1"],
            ["LinkextractorPro", "^LinkextractorPro", "1"],
            ["LinkScan/8.1a.Unix", "^LinkScan/8.1a.Unix", "1"],
            ["LNSpiderguyt", "^LNSpiderguyt", "1"],
            ["LinkWalker", "^LinkWalker", "1"],
            ["lwp-trivial", "^lwp-trivial", "1"],
            ["LWP::Simple", "^LWP::Simple", "1"],
            ["Magnet", "^Magnet", "1"],
            ["Mag-Net", "^Mag-Net", "1"],
            ["MarkWatch", "^MarkWatch", "1"],
            ["Mass Downloader", "^Mass\ Downloader", "1"],
            ["Mata.Hari", "^Mata.Hari", "1"],
            ["Memo", "^Memo", "1"],
            ["Microsoft.URL", "^Microsoft.URL", "1"],
            ["Microsoft URL Control", "^Microsoft\ URL\ Control", "1"],
            ["MIDown tool", "^MIDown\ tool", "1"],
            ["MIIxpc", "^MIIxpc", "1"],
            ["Mirror", "^Mirror", "1"],
            ["Missigua Locator", "^Missigua\ Locator", "1"],
            ["Mister PiX", "^Mister\ PiX", "1"],
            ["moget", "^moget", "1"],
            ["Mozilla/3.Mozilla", "^Mozilla/3.Mozilla/2.01", "1"],
            ["Mozilla.*NEWT", "^Mozilla.*NEWT", "1"],
            ["NAMEPROTECT", "^NAMEPROTECT", "1"],
            ["Navroad", "^Navroad", "1"],
            ["NearSite", "^NearSite", "1"],
            ["NetAnts", "^NetAnts", "1"],
            ["Netcraft", "^Netcraft", "1"],
            ["NetMechanic", "^NetMechanic", "1"],
            ["NetSpider", "^NetSpider", "1"],
            ["Net Vampire", "^Net\ Vampire", "1"],
            ["NetZIP", "^NetZIP", "1"],
            ["NextGenSearchBot", "^NextGenSearchBot", "1"],
            ["NG", "^NG", "1"],
            ["NICErsPRO", "^NICErsPRO", "1"],
            ["NimbleCrawler", "^NimbleCrawler", "1"],
            ["Ninja", "^Ninja", "1"],
            ["NPbot", "^NPbot", "1"],
            ["Octopus", "^Octopus", "1"],
            ["Offline Explorer", "^Offline\ Explorer", "1"],
            ["Offline Navigator", "^Offline\ Navigator", "1"],
            ["Openfind", "^Openfind", "1"],
            ["OutfoxBot", "^OutfoxBot", "1"],
            ["PageGrabber", "^PageGrabber", "1"],
            ["Papa Foto", "^Papa\ Foto", "1"],
            ["pavuk", "^pavuk", "1"],
            ["pcBrowser", "^pcBrowser", "1"],
            ["PHP version tracker", "^PHP\ version\ tracker", "1"],
            ["Pockey", "^Pockey", "1"],
            ["ProPowerBot", "^ProPowerBot/2.14", "1"],
            ["ProWebWalker", "^ProWebWalker", "1"],
            ["psbot", "^psbot", "1"],
            ["Pump", "^Pump", "1"],
            ["QueryN.Metasearch", "^QueryN.Metasearch", "1"],
            ["RealDownload", "^RealDownload", "1"],
            ["Reaper", "Reaper", "1"],
            ["Recorder", "Recorder", "1"],
            ["ReGet", "^ReGet", "1"],
            ["RepoMonkey", "^RepoMonkey", "1"],
            ["RMA", "^RMA", "1"],
            ["Siphon", "Siphon", "1"],
            ["sitecheck.internetseer.com", "sitecheck.internetseer.com", "1"],
            ["SiteSnagger", "^SiteSnagger", "1"],
            ["SlySearch", "^SlySearch", "1"],
            ["SmartDownload", "^SmartDownload", "1"],
            ["Snake", "^Snake", "1"],
            ["Snapbot", "^Snapbot", "1"],
            ["Snoopy", "^Snoopy", "1"],
            ["sogou", "^sogou", "1"],
            ["SpaceBison", "^SpaceBison", "1"],
            ["SpankBot", "^SpankBot", "1"],
            ["spanner", "^spanner", "1"],
            ["Sqworm", "^Sqworm", "1"],
            ["Stripper", "Stripper", "1"],
            ["Sucker", "Sucker", "1"],
            ["SuperBot", "^SuperBot", "1"],
            ["SuperHTTP", "^SuperHTTP", "1"],
            ["Surfbot", "^Surfbot", "1"],
            ["suzuran", "^suzuran", "1"],
            ["Szukacz", "^Szukacz/1.4", "1"],
            ["tAkeOut", "^tAkeOut", "1"],
            ["Teleport", "^Teleport", "1"],
            ["Telesoft", "^Telesoft", "1"],
            ["TurnitinBot", "^TurnitinBot/1.5", "1"],
            ["The.Intraformant", "^The.Intraformant", "1"],
            ["TheNomad", "^TheNomad", "1"],
            ["TightTwatBot", "^TightTwatBot", "1"],
            ["Titan", "^Titan", "1"],
            ["toCrawl/UrlDispatcher", "^toCrawl/UrlDispatcher", "1"],
            ["True_Robot", "^True_Robot", "1"],
            ["turingos", "^turingos", "1"],
            ["TurnitinBot", "^TurnitinBot", "1"],
            ["URLy.Warning", "^URLy.Warning", "1"],
            ["Vacuum", "^Vacuum", "1"],
            ["VCI", "^VCI", "1"],
            ["VoidEYE", "^VoidEYE", "1"],
            ["Web Image Collector", "^Web\ Image\ Collector", "1"],
            ["Web Sucker", "^Web\ Sucker", "1"],
            ["WebAuto", "^WebAuto", "1"],
            ["Webbandit", "^Webbandit", "1"],
            ["Webclipping.com", "^Webclipping.com", "1"],
            ["WebCopier", "^WebCopier", "1"],
            ["WebEMailExtrac.*", "^WebEMailExtrac.*", "1"],
            ["WebEnhancer", "^WebEnhancer", "1"],
            ["WebFetch", "^WebFetch", "1"],
            ["WebGo IS", "^WebGo\ IS", "1"],
            ["Web.Image.Collector", "^Web.Image.Collector", "1"],
            ["WebLeacher", "^WebLeacher", "1"],
            ["WebmasterWorldForumBot", "^WebmasterWorldForumBot", "1"],
            ["WebReaper", "^WebReaper", "1"],
            ["WebSauger", "^WebSauger", "1"],
            ["WebSite", "^WebSite", "1"],
            ["Website eXtractor", "^Website\ eXtractor", "1"],
            ["Website Quester", "^Website\ Quester", "1"],
            ["Webster", "^Webster", "1"],
            ["WebStripper", "^WebStripper", "1"],
            ["WebWhacker", "^WebWhacker", "1"],
            ["WebZIP", "^WebZIP", "1"],
            ["Whacker", "Whacker", "1"],
            ["Widow", "^Widow", "1"],
            ["WISENutbot", "^WISENutbot", "1"],
            ["WWWOFFLE", "^WWWOFFLE", "1"],
            ["WWW-Collector-E", "^WWW-Collector-E", "1"],
            ["Xaldon", "^Xaldon", "1"],
            ["Xenu", "^Xenu", "1"],
            ["Zeus", "^Zeus", "1"],
            ["Zyborg", "^Zyborg", "1"],
        ];
        $this->batchInsert('{{%stats_robots}}', ['name', 'regexp', 'is_badbot'], $rows);

    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {

        if (!(Yii::$app->db->getTableSchema('{{%stats_visitors}}', true) === null)) {
            $this->dropForeignKey(
                'fk_visitors_to_robots',
                '{{%stats_visitors}}'
            );
        }

        $this->truncateTable('{{%stats_robots}}');
        $this->dropTable('{{%stats_robots}}');
    }
}